services:
  - type: web
    name: quicknotes-backend
    env: docker
    plan: free
    dockerfilePath: QuickNotes/backend/Dockerfile  # Adjusted to the actual path
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: /app/src/notes.db
      - key: PORT
        value: 4000
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: quicknotes-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: QuickNotes/frontend/build  # Adjusted to the actual path
    autoDeploy: true
